### ISSUE TITLE
Remove duplicate CSS

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-share#113]
It seems like in the output CSS, the base `.o-share__icon` class appears for _each_ icon type. Almost definitely a mistake, but don't have time to investigate right now.

[This mixin](https://github.com/Financial-Times/o-share/blob/master/src/scss/share.scss#L52) is called for each icon type, seems like `.o-share__icon` belongs in the base mixin instead.

**Comment by chee** [comment]
yes, i think `o-share__icon` should be in the base mixin
