### ISSUE TITLE
Append "(link opens in a new window)" to screen reader text.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-share#116]
For the enhanced experience (when JavaScript is available) we open new windows for social sharing. To avoid confusion that may be caused by the appearance of new windows that were not requested by the user (https://www.w3.org/TR/WCAG20-TECHS/H83.html), append "(link opens in a new window)" to hidden social share text `.o-share__text` dynamically.

**Comment by sjparkinson** [comment]
Cavat, we'll need to remove the fix in:

* https://github.com/Financial-Times/next-video-page/pull/163
* https://github.com/Financial-Times/next-front-page/pull/1813
* https://github.com/Financial-Times/next-stream-page/pull/1978

When this is addressed in o-share.

**Comment by notlee** [comment]
Glynn kindly did this. I'm not sure how I allowed this issue to hang around 🙃
