### ISSUE TITLE
Possible to include sticky behaviour

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-share#120]
@OttlikG needs the sticky behaviour that is present on the article page for something he's working on. Do we think it's possible to include in o-share?

@wheresrhys did you originally work on this sticky behaviour or am I remembering wrong?

@notlee assigning you just for now, in case you know more about this :)

**Comment by wheresrhys** [comment]
Remembering wrong. May have been @i-like-robots

**Comment by i-like-robots** [comment]
Not me but it might have been based on one of these: https://codepen.io/i-like-robots/pen/bZXGmR or https://codepen.io/i-like-robots/pen/NRwPxL

There are a bunch of vanilla JS sticky libs out there, it should be straightforward to utilise one of those.

**Comment by chee** [comment]
I'm going to close this.
If there's someone who still needs this functionality, please open a new issue.
