### ISSUE TITLE
Require $system_code variable be set by consumers of this component

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-share#121]
We have a lot of origami-image-service requests with source=o-icons, which is actually not useful as we don't know who the real source is. E.G. Is it HTSI/FT/NAR/ScoutAsia?

This is due to the fact that the origami components hardcode a source value in their scss. E.G. https://github.com/Financial-Times/o-share/blob/4eed484759f47794e01cf5bf6400e58cf1d9b85e/demos/src/demo.scss#L13

I'm thinking when we introduce source= to the Origami-Build-Service, we update the origami components to require users pass in a $source or $system_code variable in order to use them. We can then use the $system_code/$source as the value passed to the origami-image-service URLs within the scss.

Waiting on Financial-Times/origami-build-service#67

**Comment by chee** [comment]
Closed in favour of #142
