### ISSUE TITLE
Cannot be used with o-tooltip

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-share#137]
Reported by @saldixon on Slack:

> Hi team.  I am working on creating a new tooltip (for the Share button) as part of n-messaging-client functionality (https://github.com/Financial-Times/n-messaging-client/commit/d3847a4c252c230c47c6c0b7649b5e4b428e455a). I implemented in exactly the same way as has been done before, but it does not render properly. @umbobabo helped me find the problem:  the new tooltip contains a span element, and is assigned to an element within an o-share component on the article page, and it therefore inherits the _position: absolute_ and _font-size: 12px_ properties from the o-share component styling.  Looks like the o-share css is not fully BEM, which is causing that styling to cascade to all descendent span elements?
>
> This can be observed by navigating to an article page on www.ft.com, and using toggler.ft.com to set the messageSlotTop flag variant to giftArticles...
>
> ![image (3)](https://user-images.githubusercontent.com/138944/60981448-4603fb80-a32e-11e9-8606-1e7efbd9ca10.png)
>
> Was wondering if a fix could be put in to address this?

**Comment by notlee** [comment]
As in Slack:

It’s actually an override of `o-share` [by `next-article`](https://github.com/Financial-Times/next-article/blob/master/client/components/share/_buttons-with-text.scss).

We have [an issue open to review `o-share`](https://github.com/Financial-Times/o-share/issues/135) and the modifications being made by `next-article`.

As this is an issue with `next-article` I'll close this issue.
