### ISSUE TITLE
Inconsistent Twitter Icon Response

### ISSUE THREAD

**Issue by spriggsha** [Financial-Times/o-share#29]
Seen on the Responsive Fast-FT page
![image](https://cloud.githubusercontent.com/assets/7458891/4303803/c1700daa-3e6a-11e4-8d6d-df24edce037c.png)
![image](https://cloud.githubusercontent.com/assets/7458891/4303804/c59a7708-3e6a-11e4-9f47-2b8726d6b35b.png)

The call to image.webservices.ft.com is the same each time. It's the returned icons that are different. About 50/50 which one you get.

Request URL:http://image.webservices.ft.com/v1/images/raw/ftsocial:link,ftsocial:twitter,ftsocial:facebook,ftsocial:googleplus,ftsocial:linkedin,ftsocial:stumbleupon,ftsocial:reddit,ftsocial:tumblr?width=24&source=o-share
![image](https://cloud.githubusercontent.com/assets/7458891/4303808/cfd53578-3e6a-11e4-99e4-15606286c364.png)
![image](https://cloud.githubusercontent.com/assets/7458891/4303809/d2fc6118-3e6a-11e4-8dd6-97e682eba035.png)

**Comment by kaelig** [comment]
Couldn't reproduce the error as of today, looks like caching issues may have been worked out since then.
