### ISSUE TITLE
Reddit icon rendering issue

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-share#39]
The image service doesn't render SVG to PNG well:

SVG vs PNG
![ ](http://image.webservices.ft.com/v1/images/raw/ftsocial:reddit?source=test) ![ ](http://image.webservices.ft.com/v1/images/raw/ftsocial:reddit?width=63&source=test)

Nota bene: if PNG is used as a fallback, then this bug shouldn't be fixed.

**Comment by onishiweb** [comment]
PNG should only be used as a fallback. So I don't think this is an issue.
