### ISSUE TITLE
Optimise social image files

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-share#40]
Using SVGO or similar

Icons are stored here: http://git.svc.ft.com/projects/DATA/repos/social-images/browse/src

**Comment by onishiweb** [comment]
I think the SVGs have been optimised since this was raised as an issue, @AlbertoElias you happy for this to be closed?

**Comment by AlbertoElias** [comment]
The ones in o-icons definitely have

**Comment by onishiweb** [comment]
Ok, it's not using `o-icons` yet, still on the social images set, but they look optimised to me (checked out in SVGOMG and one of the commits mentions SVGO being used as well).
