### ISSUE TITLE
Gap between image and focus ring

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-share#41]
See screenshot:
![screenshot 2015-04-13 11 57 24](https://cloud.githubusercontent.com/assets/85783/7114361/67430874-e1d4-11e4-804c-127659aa0e33.png)

Note that if we handle roundness of icons with CSS instead of the image itself (see #38), then this issue is easily fixable.

**Comment by onishiweb** [comment]
Fixed by #61
