### ISSUE TITLE
should require 'dom-delegate' instead of 'ftdomdelegate'

### ISSUE THREAD

**Issue by tomgp** [Financial-Times/o-share#43]
at the moment my project had both ftdomdelegate and dom-delegate installed, they do the same thing right?

**Comment by onishiweb** [comment]
They are both the same, just `dom-delegate` is the npm registry version. Having done a quick look through the FT repos, `ftdomdelegate` in `bower.json` seems to be the most used, and when `dom-delegate` is being used, it normally references `ftdomdelegate` so I think we're doing what the majority are doing here.
