### ISSUE TITLE
Small hit area on o-share buttons

### ISSUE THREAD

**Issue by sdbernard** [Financial-Times/o-share#59]
The current iteration has a very small hit area for the buttons

**Comment by onishiweb** [comment]
Doing a bit of looking into this. The current touch target is `36px` square.

Google (PageSpeed insights for some reason) recommends at least a `48px` square touch size (https://developers.google.com/speed/docs/insights/SizeTapTargetsAppropriately#overview). Whilst Apple recommends around a `44px` touch target size (https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LayoutandAppearance.html). So we are quite below each of those.

To address this we can either increase the size of the icon as well as the padding around it, or we could just double the size of the padding to `12px` which would increase the target area. However, Next are already removing the padding from the top and bottom of icons to fit their design so I think this might be one for design to look at?  / @alicebartlett

**Comment by onishiweb** [comment]
We're increasing the hit target to 40px in #80. I think we're going to be updating it again when we can update the buttons and I'll make sure this is kept in mind when doing so.
