### ISSUE TITLE
IG flavour share buttons

### ISSUE THREAD

**Issue by sdbernard** [Financial-Times/o-share#60]
We would like to use the o-share buttons but in their current guise they are a little bit 'shouty'. If it is possible to create a 'quieter' IG design that would be great.

This is how we do them currently

![image](https://cloud.githubusercontent.com/assets/2511348/14290064/7a8e7bb6-fb55-11e5-92c1-223fec016e6d.png)

Hover
![image](https://cloud.githubusercontent.com/assets/2511348/14290093/945825f6-fb55-11e5-995c-d0bc4403f7d9.png)

**Comment by AlbertoElias** [comment]
Hi Steve, Next are working on new icons and we're looking into implementing them, once they're finished, in a way that would allow an IG like design as well

**Comment by onishiweb** [comment]
New icon styles are in #80 @sdbernard what do you think?

**Comment by onishiweb** [comment]
Closing because of the update to square icons in #80
