### ISSUE TITLE
Strip out trailing slash from o-share-url

### ISSUE THREAD

**Issue by joannaskao** [Financial-Times/o-share#64]
URLs with a trailing slash don't work properly (at least for Facebook share). It would be great if they could get stripped out in case whoever is using this forgets to delete it from the markup.

**Comment by alicebartlett** [comment]
Can you show me an example of where this isn't working?

**Comment by alicebartlett** [comment]
Here's that tool working for an IG site with a trailing slash: 
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fig.ft.com%2Fsites%2Fbrexit-companies%2F and without a trailing slash too: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fig.ft.com%2Fsites%2Fbrexit-companies

**Comment by alicebartlett** [comment]
Closing this, going to add that tool to the README as the way Facebook caches pages does seem like a bit of a gotcha here. 

Let me know if you're still having problems with your articles.
